{"level":"error","message":"Database connection failed database \"prosync\" does not exist","name":"SequelizeConnectionError","original":{"code":"3D000","file":"postinit.c","length":93,"line":"1034","name":"error","routine":"InitPostgres","severity":"FATAL"},"parent":{"code":"3D000","file":"postinit.c","length":93,"line":"1034","name":"error","routine":"InitPostgres","severity":"FATAL"},"service":"prosync-hub-api","stack":"SequelizeConnectionError: database \"prosync\" does not exist\n    at Client._connectionCallback (e:\\projects\\ProSyncHub\\server\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (e:\\projects\\ProSyncHub\\server\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (e:\\projects\\ProSyncHub\\server\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:524:28)\n    at e:\\projects\\ProSyncHub\\server\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (e:\\projects\\ProSyncHub\\server\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (e:\\projects\\ProSyncHub\\server\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:524:28)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)","timestamp":"2025-06-27T13:37:41.892Z"}
